[build]
builder = "DOCKERFILE"
dockerfilePath = "./Backend/Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[build.env]]
key = "RAILWAY_DOCKERFILE_PATH"
value = "./Backend/Dockerfile"
